name: 'JS Actions Dependency Updater'
author: 'Tianhao Zhou'
description: 'Automated node_modules updates for GitHub Actions built with JS'
inputs:
  git-email:
    description: 'The email pull request should be associated with'
    required: false
    default: 'example@jsactionbot.com'
  git-name:
    description: 'The name pull request should be associated with'
    required: false
    default: 'JS Action Bot'
  target-branch:
    description: 'The main branch of the repository where pull requests should be sent to.'
    required: false
    default: 'master'
  temp-branch:
    description: 'The branch to get created to update the packages.'
    required: false
    default: 'chore/update-node-modules'
  title:
    description: 'The title of the pull request'
    required: false
    default: '[JS actions dependency updater] Automated JS Actions Dependency Update'
  token:
    description: 'GitHub token used to open pull requests'
    required: false
    default: 'local'
  log:
    description: 'The logging level which can be quiet, info, warning or error.'
    required: false
    default: 'quiet'
  workspace:
    description: 'The root directory of the JS project of interest.'
    required: false
    default: './'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'activity'  
  color: 'green'
